version: 2.1

orbs:
  codacy: codacy/base@0.1.0
jobs:

  checkout_and_version:
    docker:
      - image: codacy/git-version:1.0.8
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Set version
          command: /bin/git-version > .version
      - run:
          name: Set Sbt version
          command: echo "version in ThisBuild := \"$(cat .version)\"" > version.sbt
      - run:
          name: Current version
          command: cat .version
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir


  build:
    machine: true
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: Clone test project
          working_directory: ~/
          command: |
            (git -C ~/codacy-plugins-test fetch --all && 
              git -C ~/codacy-plugins-test reset --hard origin/master) || 
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - restore_cache:
          key: dependencies-{{ checksum "build.sbt" }}
      - run: 
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - run: 
          name: Publish tool docker locally
          working_directory: ~/workdir
          command: sbt 'set version in Docker := "latest"' "set name := \"$CIRCLE_PROJECT_REPONAME\"" docker:publishLocal
      - save_cache:
          key: dependencies-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
            - "~/workdir/target"
            - "~/workdir/project/target"
            - "~/workdir/project/project"
      - run:
          name: Test
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.noremove=true -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest all $CIRCLE_PROJECT_REPONAME:latest"
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME
              docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
              docker push codacy/$CIRCLE_PROJECT_REPONAME
              docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_and_version
      - build:
          context: CodacyDocker
          requires:
            - checkout_and_version
      - codacy/tag_version:
          name: tag_version
          requires:
            - build
          filters:
            branches:
              only:
                - master
